kind: PersistentVolume
apiVersion: v1
metadata:
  name: local-pv
spec:
  storageClassName: local-storage-class
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/ssd/artifactory/tank-game
