apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deploy-role
  namespace: tank-game
rules:
  - apiGroups: ["apps", ""]
    resources: ["deployments"]
    verbs: ["create", "update", "delete"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["create", "update", "delete"]
