apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deploy-rolebinding
  namespace: tank-game
subjects:
  - kind: ServiceAccount
    name: deployer-service-account
    namespace: tank-game
roleRef:
  kind: Role
  name: deploy-role
  apiGroup: rbac.authorization.k8s.io
