apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-pv-tank-game
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: harbor-pv-tank-game
  hostPath:
    path: /data/ssd/harbor/tank-game/
