---
- name: Install Jenkins
  hosts: all
  become: true
  tasks:
    - name: Add Jenkins Helm chart repository
      command: helm repo add jenkins https://charts.jenkins.io

    - name: Update Helm repositories
      command: helm repo update

    - name: Create values.yaml file
      copy:
        src: ../kubernetes/jenkins-values.yaml
        dest: $HOME/jenkins-values.yaml

    - name: Install Jenkins
      command: helm upgrade jenkins-tank-game jenkins/jenkins -f $HOME/jenkins-values.yaml -n tank-game

    - name: Wait for installation to complete
      command: helm status jenkins-tank-game

    - name: Remove values.yaml file
      file:
        path: $HOME/jenkins-values.yaml
        state: absent
