openapi: 3.0.3
info:
  version: 0.1.0
  title: tank game server api
paths:
  /login:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  pattern: /^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/
                password:
                  type: string
              required:
                - email
                - password              
      responses:
        "200":
          description: Successful response
