apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: clone-repo-task
spec:
  workspaces:
    - name: source-repo
      emptyDir: {}
  steps:
    - name: clone-repo
      image: alpine/git
      args:
        - clone
        - "--depth=1"
        - "--single-branch"
        - "--branch=$(params.gitRef)"
        - "$(params.gitUrl)"
        - "$(workspaces.source-repo.path)/src"
