pipeline {
    agent {
        docker {
            image 'harbor.flmichel.duckdns.org/tank-game/tank-game-agent:latest'
            credentialsId 'bbcb1dbb-962d-448b-92a2-27bccdab4064'
        }
    }


    stages {
        stage('Server') {
            steps {
                dir('../../server') {
                    sh 'cargo build'
                }
            }
        }
        
        stage('Game') {
            steps {
                dir('../../game') {
                    sh 'cargo build'
                }
            }
        }
        
        stage('Remote') {
            steps {
                dir('../../remote') {
                    sh 'npm install'
                    sh 'npm run build'
                }
            }
        }
    }
}