@startuml containers_definition
!include configuration.puml
AddElementTag("backendContainer", $fontColor=$ELEMENT_FONT_COLOR, $bgColor="#335DA5", $shape=EightSidedShape(), $legendText="backend container\neight sided")

!unquoted procedure player()
Person(player, Player, "One a the player of the game")
!endprocedure
!unquoted procedure game()
Container(game, "Game", "Rust", "Game which runs on a computer (Linux, Mac OS X, Windows)")
!endprocedure
!unquoted procedure remote()
Container(remote, "Remote", "JavaScript", "Web applicaiton accessed from a smartphone that is the remote for the game")
!endprocedure
!unquoted procedure server_api()
Container(server_api, "Server API", "Rust", "Provides Internet banking functionality via API", $tags="backendContainer")
!endprocedure
!unquoted procedure stun()
System_Ext(stun, "STUN Server", "The STUN server used to establish WebRTC connections")
!endprocedure
@enduml