name: Prod

on:
  push:
    branches: ["master"]

jobs:
  server:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./server

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Docker CLI
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}
          registry: harbor.flmichel.duckdns.org/tank-game

      - name: Build and Push Docker Image
        run: |
          # Your Docker build and push commands go here
          docker build -t harbor.flmichel.duckdns.org/tank-game/server:latest .
          docker push harbor.flmichel.duckdns.org/tank-game/server:latest
